from unittest.mock import DEFAULT



ACCOUNT_OK = 0
ACCOUNT_DELETE = -1

GEOMETRIC_POLICY = 0
INFINITE_POLICY = 1


ROBOT_OK = 0
ROBOT_CREATING = 2
ROBOT_PAUSE = 1
ROBOT_DESTORYING = 3
ROBOT_DELETE = -1

ORDER_FINISH = 0
ORDER_WAIT = 1
ORDER_CANCEL = 2
ORDER_Fail = 3

ORDER_BUY = 0
ORDER_SELL = 1

ORDER_NONE_REF = -1

ORDER_NONE_FLAG = -1
# ORDER_CANCEL_FLAG = 1


ROBOT_MODIFY_PAUSE_RESUME = 0
ROBOT_MODIFY_DELETE = 1

STATUS_ERROR = -1
STATUS_OK = 0

MAX_ORDER_NUM = 50
BASE_ORDER_NUM = 1
DISTANCE_RATIO = 0.1
DISTANCE_MAX = 1e-4
ORDER_DISTANCE = 1e-3

MAX_REPOST_NUM = 2
MAX_DAYS = 4

DEFAULT_API = "空"
INVALID_ACCOUNT = -1


# HUOBI_CONSTANT = 0
# BIAN_CONSTANT = 1
DEFAULT_PLANTFORM = "空"
HUOBI_STR = '火币'
BIAN_STR = '币安'
OK_STR = 'OK'
MAGIC_NUMBER = 13
OK_DELAY_TIME = 0

check_frequency = {HUOBI_STR: 200, OK_STR: 100}
plantform_array = ['火币', 'OK']
currency_arry = ["btcusdt", "ethusdt", "ltcusdt"]