# Generated by Django 2.2.5 on 2022-08-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.IntegerField(db_column='account_id', primary_key=True, serialize=False)),
                ('api_id', models.IntegerField(db_column='api_id')),
                ('system_id', models.IntegerField(db_column='system_id')),
                ('account_nickname', models.CharField(db_column='account_nickname', default='', max_length=300)),
                ('account_password', models.CharField(db_column='account_password', default='', max_length=100)),
                ('account_status', models.IntegerField(db_column='account_status', default=0)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Api',
            fields=[
                ('api_id', models.IntegerField(db_column='api_id', primary_key=True, serialize=False)),
                ('api_key', models.CharField(db_column='api_key', max_length=100)),
                ('secret_key', models.CharField(db_column='secret_key', max_length=100)),
            ],
            options={
                'db_table': 'api',
            },
        ),
        migrations.CreateModel(
            name='GeometricPolicy',
            fields=[
                ('policy_id', models.IntegerField(db_column='policy_id', primary_key=True, serialize=False)),
                ('max_price', models.FloatField(db_column='max_price', default=0)),
                ('min_price', models.FloatField(db_column='min_price', default=0)),
                ('grid_num', models.IntegerField(db_column='grid_num', default=0)),
                ('grid_invest', models.FloatField(db_column='grid_invest')),
                ('expect_money', models.FloatField(db_column='expect_money', default=0)),
                ('grid_profit_rate', models.FloatField(db_column='grid_profit_rate', default=0)),
            ],
            options={
                'db_table': 'geometric_policy',
            },
        ),
        migrations.CreateModel(
            name='InfinitePolicy',
            fields=[
                ('policy_id', models.IntegerField(db_column='policy_id', primary_key=True, serialize=False)),
                ('max_price', models.FloatField(db_column='max_price', default=0)),
                ('min_price', models.FloatField(db_column='min_price', default=0)),
                ('grid_invest', models.FloatField(db_column='grid_invest')),
                ('rate_buy', models.FloatField(db_column='rate_buy')),
                ('rate_sell', models.FloatField(db_column='rate_sell')),
                ('expect_money', models.FloatField(db_column='expect_money', default=0)),
            ],
            options={
                'db_table': 'infinite_policy',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(db_column='order_id', primary_key=True, serialize=False)),
                ('order_record_id', models.IntegerField(db_column='order_record_id')),
                ('robot_id', models.IntegerField(db_column='robot_id')),
                ('order_currency_type', models.CharField(db_column='order_currency_type', max_length=20)),
                ('order_amount', models.FloatField(db_column='order_amount')),
                ('order_price', models.FloatField(db_column='order_price')),
                ('order_type', models.IntegerField(db_column='order_type')),
                ('order_status', models.IntegerField(db_column='order_status')),
                ('order_transfer_fees', models.FloatField(db_column='order_transfer_fees', default=0)),
                ('order_create_time', models.DateTimeField(db_column='order_create_time')),
                ('order_finish_time', models.DateTimeField(db_column='order_finish_time', null=True)),
                ('order_refer_id', models.IntegerField(db_column='order_refer_id', default=-1)),
                ('order_flag', models.IntegerField(db_column='order_flag', default=0)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('robot_id', models.IntegerField(db_column='robot_id', primary_key=True, serialize=False)),
                ('robot_account_id', models.IntegerField(db_column='robot_account_id', default=-1)),
                ('robot_summary_id', models.IntegerField(db_column='robot_summary_id')),
                ('robot_policy_type', models.IntegerField(db_column='robot_policy_type')),
                ('robot_currency_type', models.CharField(db_column='robot_currency_type', max_length=20)),
                ('robot_policy_id', models.IntegerField(db_column='robot_policy_id')),
                ('robot_status', models.IntegerField(db_column='robot_status', default=0)),
                ('robot_create_time', models.DateTimeField(db_column='robot_create_time')),
            ],
            options={
                'db_table': 'robot',
            },
        ),
        migrations.CreateModel(
            name='RobotSummary',
            fields=[
                ('summary_id', models.IntegerField(db_column='summary_id', primary_key=True, serialize=False)),
                ('invested_money', models.FloatField(db_column='invested_money', default=0.0)),
                ('hold_currency_num', models.FloatField(db_column='hold_currency_num', default=0.0)),
                ('total_transfer_fee', models.FloatField(db_column='total_transfer_fee', default=0.0)),
                ('profit', models.FloatField(db_column='profit', default=0.0)),
            ],
            options={
                'db_table': 'robot_summary',
            },
        ),
    ]
