# Generated by Django 3.2.13 on 2022-09-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='robot_order',
        ),
    ]
