# Generated by Django 3.2.13 on 2022-09-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitApp', '0002_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_record_id',
            field=models.CharField(db_column='order_record_id', max_length=20),
        ),
    ]
